# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand.

createCohortIncidenceModuleSpecifications <- function(irDesign = NULL) {
  analysis <- list()
  for (name in names(formals(createCohortIncidenceModuleSpecifications))) {
    analysis[[name]] <- get(name)
  }

  specifications <- list(module = "CohortIncidenceModule",
                         version = "0.2.0",
                         remoteRepo = "github.com",
                         remoteUsername = "ohdsi",
                         settings = analysis)
  class(specifications) <- c("CohortIncidenceModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}
